# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys, csv
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(657, 547)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.editPort = QtWidgets.QLineEdit(self.centralwidget)
        self.editPort.setGeometry(QtCore.QRect(440, 210, 181, 22))
        self.editPort.setObjectName("editPort")
        self.editHashDigest = QtWidgets.QLineEdit(self.centralwidget)
        self.editHashDigest.setGeometry(QtCore.QRect(440, 100, 181, 22))
        self.editHashDigest.setObjectName("editHashDigest")
        self.dateTime = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTime.setGeometry(QtCore.QRect(440, 60, 181, 22))
        self.dateTime.setObjectName("dateTime")
        self.editCity = QtWidgets.QLineEdit(self.centralwidget)
        self.editCity.setGeometry(QtCore.QRect(440, 310, 181, 22))
        self.editCity.setText("")
        self.editCity.setObjectName("editCity")
        self.btnConfirm = QtWidgets.QPushButton(self.centralwidget)
        self.btnConfirm.setGeometry(QtCore.QRect(530, 460, 93, 28))
        self.btnConfirm.setObjectName("btnConfirm")
        self.lblIp = QtWidgets.QLabel(self.centralwidget)
        self.lblIp.setGeometry(QtCore.QRect(340, 180, 81, 16))
        self.lblIp.setObjectName("lblIp")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(20, 10, 279, 28))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.btnExport = QtWidgets.QPushButton(self.splitter)
        self.btnExport.setObjectName("btnExport")
        self.btnImport = QtWidgets.QPushButton(self.splitter)
        self.btnImport.setObjectName("btnImport")
        self.btnReport = QtWidgets.QPushButton(self.splitter)
        self.btnReport.setObjectName("btnReport")
        self.lblPort = QtWidgets.QLabel(self.centralwidget)
        self.lblPort.setGeometry(QtCore.QRect(340, 210, 81, 16))
        self.lblPort.setObjectName("lblPort")
        self.lblOrganization = QtWidgets.QLabel(self.centralwidget)
        self.lblOrganization.setGeometry(QtCore.QRect(340, 140, 81, 16))
        self.lblOrganization.setObjectName("lblOrganization")
        self.lblRegion = QtWidgets.QLabel(self.centralwidget)
        self.lblRegion.setGeometry(QtCore.QRect(340, 280, 81, 16))
        self.lblRegion.setObjectName("lblRegion")
        self.editOrganization = QtWidgets.QLineEdit(self.centralwidget)
        self.editOrganization.setGeometry(QtCore.QRect(440, 140, 181, 22))
        self.editOrganization.setObjectName("editOrganization")
        self.lblDate = QtWidgets.QLabel(self.centralwidget)
        self.lblDate.setGeometry(QtCore.QRect(340, 60, 61, 16))
        self.lblDate.setObjectName("lblDate")
        self.editIp = QtWidgets.QLineEdit(self.centralwidget)
        self.editIp.setGeometry(QtCore.QRect(440, 180, 181, 22))
        self.editIp.setObjectName("editIp")
        self.lblCity = QtWidgets.QLabel(self.centralwidget)
        self.lblCity.setGeometry(QtCore.QRect(340, 310, 81, 16))
        self.lblCity.setObjectName("lblCity")
        self.lblHashDigest = QtWidgets.QLabel(self.centralwidget)
        self.lblHashDigest.setGeometry(QtCore.QRect(340, 100, 71, 16))
        self.lblHashDigest.setObjectName("lblHashDigest")
        self.lblGeo = QtWidgets.QLabel(self.centralwidget)
        self.lblGeo.setGeometry(QtCore.QRect(340, 250, 81, 16))
        self.lblGeo.setObjectName("lblGeo")
        self.lblMain = QtWidgets.QLabel(self.centralwidget)
        self.lblMain.setGeometry(QtCore.QRect(344, 20, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.lblMain.setFont(font)
        self.lblMain.setAlignment(QtCore.Qt.AlignCenter)
        self.lblMain.setObjectName("lblMain")
        self.editGeo = QtWidgets.QLineEdit(self.centralwidget)
        self.editGeo.setGeometry(QtCore.QRect(440, 250, 181, 22))
        self.editGeo.setObjectName("editGeo")
        self.editRegion = QtWidgets.QLineEdit(self.centralwidget)
        self.editRegion.setGeometry(QtCore.QRect(440, 280, 181, 22))
        self.editRegion.setObjectName("editRegion")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(20, 50, 281, 431))
        self.tableView.setObjectName("tableView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 657, 26))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
  

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnConfirm.setText(_translate("MainWindow", "Confirm"))
        self.lblIp.setText(_translate("MainWindow", "IP:"))
        self.btnExport.setText(_translate("MainWindow", "Export"))
        self.btnImport.setText(_translate("MainWindow", "Import"))
        self.btnReport.setText(_translate("MainWindow", "Report"))
        self.lblPort.setText(_translate("MainWindow", "Port:"))
        self.lblOrganization.setText(_translate("MainWindow", "Organization:"))
        self.lblRegion.setText(_translate("MainWindow", "Region:"))
        self.lblDate.setText(_translate("MainWindow", "Date:"))
        self.lblCity.setText(_translate("MainWindow", "City:"))
        self.lblHashDigest.setText(_translate("MainWindow", "Hash Digest:"))
        self.lblGeo.setText(_translate("MainWindow", "Geography:"))
        self.lblMain.setText(_translate("MainWindow", "Data View"))
        self.menuAbout.setToolTip(_translate("MainWindow", "About the tool"))
        self.menuAbout.setStatusTip(_translate("MainWindow", "About the tool"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))

    def codeSetup(self):
        self.model = QtGui.QStandardItemModel(MainWindow)
        self.tableView.setModel(self.model)
        self.btnImport.clicked.connect(self.importCSV)
        self.btnReport.clicked.connect(self.reportIncident)

        

    def importCSV(self):
        filenames, _filter = QtWidgets.QFileDialog.getOpenFileNames(None, "Select Data Files", '/home', "CSV Files(*.csv)")
        for filename in filenames:            
            with open(filename, "r") as fileInput:
                for row in csv.reader(fileInput):
                    items = [
                        QtGui.QStandardItem(field)
                        for field in row
                    ]
                    self.model.appendRow(items)


    def reportIncident(self):
        #self.model = QtGui.QStandardItemModel(MainWindow)
        #self.tableView.setModel(self.model)
        self.tableView.clearSpans()

    def about(self):
        pass

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    ui.codeSetup()
    MainWindow.show()
    sys.exit(app.exec_())
